type: google.api.Service
config_version: 3
name: classifier.grpc.endpoints.infra-terraform-plygrd.cloud.goog
title: classifier
apis:
- name: classify.Classify
usage:
  rules:
  # ListShelves methods can be called without an API Key.
  - selector: "*"
    allow_unregistered_calls: true